### ISSUE TITLE
hpgl.aoizora.org is not responding

### ISSUE THREAD

**Issue by perrygeo** [hpgl/hpgl#2]
http://hpgl.aoizora.org/ gives a 404.

Where can I find documentation on HGPL?

**Comment by karimbahgat** [comment]
I had the same issue with the old website and found a newer one at http://hpgl.mit-ufa.com/

Specifically, the documentation seems to be in a pdf document at http://hpgl.mit-ufa.com/hpgl_0.9.9_manual_english.pdf

**Comment by Snegovikufa** [comment]
Our team moved HGPL website from aoizora hosting, but we have no time to update links and documentation. As karimbahgat said, you can find documentation and other information at http://hpgl.mit-ufa.com/ website
