### ISSUE TITLE
Update links to newest website

### ISSUE THREAD

**Issue by karimbahgat** [hpgl/hpgl#3]
I noticed the links on this Github repo in the description and readme.md are still pointing to the old (dead) links, instead of to the new site at http://hpgl.mit-ufa.com. While I realize from #1 that there are no active developers working on this anymore, it would greatly increase access to your lib if the links in the description and readme.md could be updated. If you do it, you might as well update the version number from 9.3 to 9.9 which doesnt seem to have been updated in the readme.md, just to avoid confusion.

**Comment by Snegovikufa** [comment]
Thank you karimbahgat, I will update links and readme very soon.

**Comment by Snegovikufa** [comment]
@karimbahgat I updated version, readme file and removed bad links
