### ISSUE TITLE
Confusing readme.md

### ISSUE THREAD

**Issue by mwtoews** [hpgl/hpgl#7]
There are a few old/outdated/confusing bits of information in the `readme.md` file(s):

1. There are two nearly identical readme.md files: one in the main directory and another in src. There  should be only one of these, possibly with a symbolic link to the other (if that's important).
2. Build: CLAPACK-3.1.1.1 is required, but this detail is not documented
3. Build: boost::python is deprecated and replaced by CTypes, but it is currently documented as a requirement
4. License: only readme.md describes this software with a GPL version 2 licence, whereas every other aspect of this project describes a BSD license. This needs to be more explicit, as they are different and conflicting licences.

**Comment by Snegovikufa** [comment]
Hello, @mwtoews. 
Thank you for issue!
I updated readme and license in repository.
Unfortunately project is not maintained for long time. Also I have some limitations as maintainer. I don't have access for hpgl account anymore. So, I cannot update links and mark repository as archive.

**Comment by mwtoews** [comment]
@Snegovikufa thanks for your speedy fix! I think you addressed the main points, so I'll close this issue.
