### ISSUE TITLE
sgs method error in c++ build

### ISSUE THREAD

**Issue by tantelu** [hpgl/hpgl#8]
some error when build c++ code in vs 2019 
see readme from https://github.com/tantelu/HPGL-

**Comment by Snegovikufa** [comment]
Hello, @tantelu !

I appreciate your help. I am going to check that code compiles and runs successfully and then I will merge your changes to repository. I created pull request #9 for that

**Comment by tantelu** [comment]
@Snegovikufa   the error need  change  'struct sgs_params_t'  to   'class sgs_params_t' in  file  api_helpers.hpp
